export enum Exceptions {
    INSUFFICIENT_BALANCE = "insufficient_balance",
    UNKNOWN_ERROR = "unknown_error",
    CONDITIONS_NOT_MET = "conditions_not_met",
    INCORRECT_ACCESS_TOKEN = "incorrect_access_token",
    UNAUTHORIZED = "unauthorized",
    ACCESS_DENY = "access_deny",
    PRODUCT_NOT_FOUND = "product_not_found",
    ALREADY_COMPLETE = "already_complete",
    ALREADY_EXIST = "already_exist",
    INVALID_CODE = "invalid_code",
    USER_NOT_FOUND = "user_not_found",
    WITHDRAW_TEMPORARY_NOT_AVAILABLE="withdraw_temporary_not_available",
    ITEM_NOT_FOUND = "item_not_found",
    INCORRECT_DATE = "incorrect_date",
    INCORRECT_TYPE = "incorrect_type",
    CURRENCY_ERROR = "currency_error",
    TOO_LARGE_INTERVAL = "too_large_interval",
    SALE_COMPLETE = "sale_complete",
}
